# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Project Management Blog"
description: >
  The road to Scrum

url: http://idmontie.github.io/project-management-blog/
baseurl: /project-management-blog

#blog logo
logo: "http://idmontie.github.io/project-management-blog/assets/images/logo.png"
# blog cover
cover: "http://idmontie.github.io/project-management-blog/assets/images/laptop-background.jpg"

name: 'Ivan Montiel'
author: 'Ivan Montiel'
author_image: "https://avatars3.githubusercontent.com/u/412382?v=3&s=460"

paginate:	5

